import test,{before,after,beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createMediaTestDatabase} from './helpers/media-database.mjs';
const owner='11111111-1111-4111-8111-111111111111',admin='33333333-3333-4333-8333-333333333333',foreign='44444444-4444-4444-8444-444444444444',profile='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
let db;
before(async()=>{db=await createMediaTestDatabase(true);await db.exec('create policy profiles_admin_update on company_profiles for update to authenticated using (exists(select 1 from portal_admins where user_id=auth.uid())) with check (exists(select 1 from portal_admins where user_id=auth.uid()));');for(const file of ['20260924155258_admin_company_media_editor.sql','20260929142000_replace_profile_gallery_image.sql'])await db.exec(await readFile(new URL('../supabase/migrations/'+file,import.meta.url),'utf8'));await db.query('insert into portal_admins values ($1)',[admin]);await db.query("insert into companies values ($1,$1,'Firma')",[owner]);await db.query("insert into company_profiles(id,company_id,display_name,status) values ($1,$2,'Firma','pending')",[profile,owner]);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[admin]);await db.query("select review_company_profile_with_categories($1,'approved',array['heizung'])",[profile]);await db.exec(await readFile(new URL('../supabase/migrations/20261010160000_profile_gallery_legacy_management.sql',import.meta.url),'utf8'));});
after(()=>db?.close());beforeEach(()=>db.exec('begin'));afterEach(()=>db.exec('rollback'));
async function actor(id,role='authenticated'){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,true)",[id]);await db.exec('set local role '+role);}
const paths=n=>Array.from({length:n},(_,i)=>`profiles/${profile}/gallery/00000000-0000-4000-8000-${String(i).padStart(12,'0')}.png`);
async function stored(n){const result=paths(n);for(const path of result)await db.query("insert into storage.objects(bucket_id,name) values ('company-media',$1)",[path]);return result;}
async function blocked(sql,args=[]){await db.exec('savepoint denied');await assert.rejects(db.query(sql,args));await db.exec('rollback to savepoint denied; release savepoint denied');}
test('migration changes no existing rows and adds only readonly public gallery marker',async()=>{assert.deepEqual((await db.query('select status,gallery_initialized from company_profiles where id=$1',[profile])).rows,[{status:'approved',gallery_initialized:false}]);await actor(owner);await blocked('update company_profiles set gallery_initialized=true where id=$1',[profile]);});
test('admin atomically adopts 33 images, preserves order/status and cannot run adoption twice',async()=>{const list=await stored(33);await actor(admin);await db.query('select initialize_profile_gallery($1,$2::text[],$3::text[])',[profile,list,list.map((_,i)=>'Bild '+i)]);assert.equal((await db.query('select * from company_profile_images where profile_id=$1 order by sort_order',[profile])).rows.length,33);assert.deepEqual((await db.query('select status,gallery_initialized from company_profiles where id=$1',[profile])).rows,[{status:'approved',gallery_initialized:true}]);await blocked('select initialize_profile_gallery($1,$2::text[],$3::text[])',[profile,list,list]);});
test('owner, foreign account and anon cannot execute admin adoption',async()=>{const list=await stored(1);for(const [id,role] of [[owner,'authenticated'],[foreign,'authenticated'],['','anon']]){await actor(id,role);await blocked('select initialize_profile_gallery($1,$2::text[],$3::text[])',[profile,list,['Bild']]);}});
test('invalid object, foreign path, duplicate path and malformed arrays rollback whole adoption',async()=>{const list=await stored(2);await actor(admin);for(const [p,a] of [[[],[]],[list,['one']],[['invalid'],['one']],[[list[0],list[0]],['a','b']],[[list[0],list[1].replace(profile,foreign)],['a','b']],[[list[0],paths(3)[2]],['a','b']]]){await blocked('select initialize_profile_gallery($1,$2::text[],$3::text[])',[profile,p,a]);assert.equal((await db.query('select * from company_profile_images where profile_id=$1',[profile])).rows.length,0);assert.equal((await db.query('select gallery_initialized from company_profiles where id=$1',[profile])).rows[0].gallery_initialized,false);}});
test('40 images fit and image 41 remains rejected; removal keeps marker and existing owner isolation',async()=>{const list=await stored(41);await actor(admin);await db.query('select initialize_profile_gallery($1,$2::text[],$3::text[])',[profile,list.slice(0,40),list.slice(0,40)]);await blocked('insert into company_profile_images(profile_id,storage_path) values($1,$2)',[profile,list[40]]);await actor(foreign);assert.equal((await db.query('delete from company_profile_images where profile_id=$1 returning id',[profile])).rows.length,0);await actor(admin);await db.query('delete from company_profile_images where profile_id=$1',[profile]);assert.equal((await db.query('select gallery_initialized from company_profiles where id=$1',[profile])).rows[0].gallery_initialized,true);});
test('public reads still require approved profile and cannot invoke RPC; function remains invoker',async()=>{const list=await stored(1);await actor(admin);await db.query('select initialize_profile_gallery($1,$2::text[],$3::text[])',[profile,list,['Bild']]);await actor('','anon');assert.equal((await db.query('select id from company_profile_images where profile_id=$1',[profile])).rows.length,1);await actor(admin);await db.query("update company_profiles set status='draft' where id=$1",[profile]);await actor('','anon');assert.equal((await db.query('select id from company_profile_images where profile_id=$1',[profile])).rows.length,0);await db.exec('reset role');assert.equal((await db.query("select prosecdef from pg_proc where oid='public.initialize_profile_gallery(uuid,text[],text[])'::regprocedure")).rows[0].prosecdef,false);});
