import test from 'node:test';import assert from 'node:assert/strict';import {registerHooks} from 'node:module';import {readFileSync} from 'node:fs';import {transpileModule,ModuleKind} from 'typescript';
registerHooks({resolve(s,c,next){const stub=code=>({url:'data:text/javascript,'+encodeURIComponent(code),shortCircuit:true});if(s==='server-only')return stub('export {}');if(c.parentURL?.endsWith('/initialize-legacy-gallery.ts')){if(s==='./admin-review')return stub('export const loadReviewProfile=async()=>globalThis.galleryFixture.review;');if(s==='./company-presentation')return stub('export const companyProfileListing=()=>({});');if(s==='./reiseportal-directory')return stub('export const withLegacyImages=()=>({images:globalThis.galleryFixture.images});');if(s==='./media-library-server')return stub('export const prepareLibraryImageCopy=async(_c,a)=>{const f=globalThis.galleryFixture;f.copies.push(a.id);return f.copyError?{error:"copy failed"}:{path:"profiles/p/gallery/"+a.id+".png"};}');}return next(s,c);}});
await import('./helpers/load-ts.mjs');const {initializeLegacyGallery}=await import('../src/lib/initialize-legacy-gallery.ts');
const profile='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
function setup({count=17,access='admin',ready=true,initialized=false,rows=[],missing=false,copyError=false,rpcError=false}={}){const images=Array.from({length:count},(_,i)=>({src:'/legacy-'+i+'.png',alt:'Bild '+i}));const f=globalThis.galleryFixture={review:{access,profile:{id:profile,company_profile_images:rows}},images,copies:[],copyError,rpc:[],filters:[]};return {from(table){const q={select(){return q;},eq(k,v){f.filters.push({table,k,v});return q;},is(){return q;},in(k,v){f.filters.push({table,k,v});return q;},async maybeSingle(){return {data:ready?{gallery_initialized:initialized}:null,error:ready?null:{code:'42703'}};},then(resolve,reject){return Promise.resolve({data:missing?[]:images.map((im,i)=>({id:String(i),storage_path:im.src,profile_id:profile,bucket_id:'project-media',kind:'gallery'})),error:null}).then(resolve,reject);}};return q;},async rpc(name,args){f.rpc.push({name,args});return {error:rpcError?{}:null};}};}
test('missing migration, unauthorized caller and already changed gallery never copy/write',async()=>{for(const options of [{ready:false},{access:'owner'},{initialized:true},{rows:[{id:'existing'}]}]){assert.ok((await initializeLegacyGallery(setup(options),profile)).error);assert.equal(globalThis.galleryFixture.copies.length,0);assert.equal(globalThis.galleryFixture.rpc.length,0);}});
test('source coverage is complete before copying; all 33 source images go to one atomic RPC in order',async()=>{assert.ok((await initializeLegacyGallery(setup({missing:true}),profile)).error);assert.equal(globalThis.galleryFixture.copies.length,0);assert.ok((await initializeLegacyGallery(setup({count:33}),profile)).success);const f=globalThis.galleryFixture;assert.equal(f.copies.length,33);assert.equal(f.rpc.length,1);assert.equal(f.rpc[0].name,'initialize_profile_gallery');assert.equal(f.rpc[0].args.p_profile,profile);assert.deepEqual(f.rpc[0].args.p_alts,f.images.map(i=>i.alt));assert.ok(f.filters.some(v=>v.table==='media_library_assets'&&v.k==='profile_id'&&v.v===profile));});
test('copy failures never submit a partial gallery; conflict failure does not report success',async()=>{assert.ok((await initializeLegacyGallery(setup({copyError:true}),profile)).error);assert.equal(globalThis.galleryFixture.rpc.length,0);assert.ok((await initializeLegacyGallery(setup({rpcError:true}),profile)).error);assert.equal(globalThis.galleryFixture.rpc.length,1);});
test('empty/oversized historical albums fail safely',async()=>{for(const count of [0,41]){assert.ok((await initializeLegacyGallery(setup({count}),profile)).error);assert.equal(globalThis.galleryFixture.copies.length,0);}});
const directory=readFileSync(new URL('../src/lib/reiseportal-directory.ts',import.meta.url),'utf8');const fn=directory.slice(directory.indexOf('export function withLegacyImages'),directory.indexOf('async function loadDirectoryPackages'));
const compiled=transpileModule('const reiseportalPreview=[], importedJoomlaMedia={}, legacyDirectoryMedia={}, travelPhotos={}; const verifiedProviderMedia={legacy:{images:[{src:"/legacy.png",alt:"Legacy"}]}}; const providerTravelImage=()=>undefined;'+fn,{compilerOptions:{module:ModuleKind.ESNext}}).outputText;const {withLegacyImages}=await import('data:text/javascript,'+encodeURIComponent(compiled));
test('initialized empty gallery never resurrects fallback; untouched legacy and existing canonical media are preserved',()=>{const listing={slug:'legacy',images:[],location:{region:'',country:'Deutschland'}};assert.equal(withLegacyImages(listing).images.length,1);assert.equal(withLegacyImages({...listing,galleryInitialized:true}).images.length,0);const images=[{src:'/canonical.png',alt:'Saved'}];assert.deepEqual(withLegacyImages({...listing,images}).images,images);});
