-- Correct the pre-existing Bayern column default only on this controlled import.
-- No previously existing profile or company is changed. Idempotent on re-run.
UPDATE public.company_profiles p SET region=s.region
FROM (VALUES
  ('apartbauernhof-valrunzhof', NULL, 'Österreich'),
  ('hotel-ravelli-luxury-spa', NULL, 'Italien'),
  ('der-koenigsleitner-romantik-zu-zweit', NULL, 'Österreich'),
  ('wellnesshotel-almhof-call', NULL, 'Italien'),
  ('rhoen-park-aktiv-resort', NULL, 'Deutschland'),
  ('mintrops-land-hotel', NULL, 'Deutschland'),
  ('landgut-ramshof', NULL, 'Deutschland'),
  ('pletzer-resorts-bayrischzell', NULL, 'Deutschland'),
  ('lindner-hotel-koeln-city-plaza', NULL, 'Deutschland'),
  ('schlosshotel-ralswiek', NULL, 'Deutschland'),
  ('hotel-godewind', NULL, 'Deutschland'),
  ('oewers-wellness-und-spa-hotel', NULL, 'Deutschland'),
  ('landhotel-talblick', NULL, 'Deutschland'),
  ('laerchenhof', NULL, 'Österreich'),
  ('haus-terra-ferienwohnung', NULL, 'Österreich'),
  ('hotel-mondschein', NULL, 'Österreich'),
  ('feelfree-nature-resort', NULL, 'Österreich'),
  ('alpenhotel-montafon', NULL, 'Österreich'),
  ('kesselgrub', NULL, 'Österreich'),
  ('small-und-beautiful-hotel-gnaid', NULL, 'Italien'),
  ('golf-und-sporthotel-hof-maran', NULL, 'Schweiz'),
  ('wellnesshotel-golfpanorama', NULL, 'Schweiz'),
  ('kaiser-hans-natur-residence', NULL, 'Italien'),
  ('pension-steingarten', NULL, 'Italien'),
  ('stroblhof', NULL, 'Italien'),
  ('kronplatz', NULL, 'Italien'),
  ('familienhotel-und-kinderhotel-sonnwies', NULL, 'Italien'),
  ('alfseeferien-und-erlebnispark', NULL, 'Deutschland'),
  ('blausee', NULL, 'Schweiz'),
  ('kemmeriboden-bad', NULL, 'Italien'),
  ('rue-blanch', NULL, 'Italien'),
  ('schwarzwaelderhof', NULL, 'Deutschland'),
  ('camping-resort-allweglehen', NULL, 'Deutschland'),
  ('the-chedi', NULL, 'Schweiz'),
  ('jaegeralpe', NULL, 'Österreich'),
  ('feldhof-dolcevita-resort', NULL, 'Italien'),
  ('sub-aqua-tauchreisen', NULL, 'Deutschland'),
  ('platzl-hotel', NULL, 'Deutschland'),
  ('oversum-vital-resort-im-hochsauerland', NULL, 'Deutschland'),
  ('das-5-sterne-wellness-hotel-stock-resort', 'Tirol', 'Österreich'),
  ('ostsee-barfusspark', NULL, 'Deutschland'),
  ('urlaub-auf-borkum', NULL, 'Deutschland'),
  ('city-apart-dresden', NULL, 'Deutschland'),
  ('ferienwohnung-sieber', NULL, 'Deutschland'),
  ('landgasthof-neue-schaenke', NULL, 'Deutschland')
) AS s(slug,region,country), public.companies c
WHERE p.company_id=c.id AND p.slug=s.slug AND p.country=s.country
  AND c.owner_user_id IS NULL AND p.status='approved' AND p.region IS DISTINCT FROM s.region;
